project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  title: "Geburtstagsgeschenk 2025"
  navbar:
    right:
      - icon: github
        href: "https://github.com/Haon2005/318_B_KI_2025"
        aria-label: "GitHub"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Begrüßung"
        contents:
          - href: index.qmd
            text: "Willkommen & Gratulation"
      - section: "Grundlagen"
        contents:
          - href: ki_allgemein.qmd
            text: "KI im Allgemeinen"
          - href: ki_philosophische_Sicht.qmd
            text: "Ist das wirklich KI?"
      - section: "Wie LLMs funktionieren"
        contents:
          - href: konzept_llm.qmd
            text: "Grundkonzept LLM"
          - href: vektor_embedding.qmd
            text: "Vektor-Embedding"
          - href: deterministisch_vs_probabilistisch.qmd
            text: "Deterministisch vs. Probabilistisch"
      - section: "Vorteile & Risiken"
        contents:
          - href: chancen_risiken.qmd
            text: "Chancen & Risiken"
      - href: abschied.qmd
        text: "Verabschiedung"

format:
  html:
    theme:
      light: [cerulean]
      dark: [darkly]
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    toc-location: right
