---
title: Chancen & Risiken
---

Bevor wir zum Ende kommen, ist es bei einem Thema wie diesem unvermeidbar, auch über die Chancen und Gefahren von KI und LLMs zu sprechen.

## Chancen

- **Automatisierung:** Es ist ein neuer technologischer Schritt, der sehr vieles automatisieren kann. Dadurch wird die Produktivität der Gesellschaft stark steigen können.
- **Individualbetreuung:** Es ist viel leichter, dafür zu sorgen, dass jede Person für ihr spezifisches Problem eine Lösung bekommt. Das funktioniert auch in Schulen und beim Lernen sehr gut.
- **Wissenschaft:** Die Analyse von riesigen Datenmengen wird leichter, ebenso wie Simulationen oder die Erstellung neuer komplexer Systeme (z.B. Proteine).
- **Werkzeug:** Die KI kann z.B. zum Erstellen von Webseiten wie dieser genutzt werden, sie kann zum Programmieren genutzt werden und für vieles in vielen Bereichen.

## Gefahren

- **Automatisierung** bedeutet immer auch Arbeitsplatzverlust, mehr Frustration in der Bevölkerung, größeres Krisenpotential
- **Individualbetreuung** bedeutet immer auch weniger soziale Interaktion, was zu mehr psychisch Kranken und mehr Vereinsamung führen kann.
- **Bias:** KI lernt aus Datensätzen, wenn die diskriminierend sind, ist die KI es auch
- **Fehlinformationen:** Ähnlich wie bei Taschenrechnern & Co. wird dem System oft mehr geglaubt als der eigenen Intuition. Das heißt, Fehler werden seltener bemerkt.
- **Manipulation:** Konzerne und Länder können KI auf bestimmte Trigger-Worte bestimmt reagieren lassen [Beispiel Qwens Einschränkungen (bis unten lesen!)](https://huggingface.co/blog/leonardlin/chinese-llm-censorship-analysis)
- **Falsches Selbstbewusstsein:** LLMs sind darauf trainiert, freundlich und nett zu sein. Dazu gehört auch, einer Person, die für etwas eigentlich nicht bereit ist, Mut zuzusprechen. Das heißt, wenn ich eine KI frage: "Bin ich jetzt gut genug auf die Prüfung vorbereitet?", wird die KI mir nicht die Wahrheit als Antwort geben, sondern ein: "Du schaffst das!" Hierdurch wird falsche Sicherheit erzeugt.
- **Fehlende Motivation:** Ähnlich wie beim Internet ist es nun noch einfacher, spezifisches Wissen zu lernen. Jeder kann alles lernen, und das relativ schnell. Das sorgt leider auch dafür, dass ein großer Teil der Gesellschaft kein Interesse mehr daran hat, sich damit auseinanderzusetzen. Beispiel Schule: Viele SchülerInnen lösen ihre Hausaufgaben nur noch mit KI. Kann man es ihnen verübeln? Nein. Ist es gut für ihre Bildung? Nein.
- **Datenschutz:** Der Einsatz von KI wird auf kurz oder lang dafür sorgen, dass die Privatsphäre des Individuums immer weiter eingeschränkt wird. (Wo es früher noch möglich war, manchmal ein bisschen "dumme Sachen" anzustellen, wird das irgendwann nicht mehr möglich sein, weil alles mit Kameras ausgestattet ist, die Bewegungen automatisch wahrnehmen und melden.)
Das letzte war ein wenig sehr dystopisch aber betrachten wir alleine die automatische Kennzeichenerfassung von Kennzeichen an vielen Ampeln heute. 

## Zusammenfassung
Klar, KI ist eine geniale Erfindung. ABER, wie viele auf der Konferenz, an der ich teilnehmen durfte, feststellten: KI ist besonders dann nützlich, wenn man zu einem Thema bereits etwas weiß. Sich mit KI fortzubilden, geht unglaublich schnell und gut. Aber etwas Unbekanntes zu lernen (oder als unerfahrene Person so etwas zu nutzen), ist nicht zu empfehlen.
Dabei ging es noch gar nicht um die Thematik der möglichen Terrorhilfe $\dots$ Wie schlimm wird Terror, wenn alle Terroristen in der Lage sind, innerhalb von ein paar Stunden herauszufinden, wie man möglichst effizient möglichst viele Zivilisten tötet? (Prima von einer lokalen KI bestimmt $\dots$).

Nach diesem hoffentlich nicht zu besorgniserregenden Ende geht es weiter beim [Abschied](abschied.html).